version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Exclude experimental and preview packages from auto-updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*-experimental*"
      - dependency-name: "*-preview*"
      - dependency-name: "*-alpha*"
      - dependency-name: "*-beta*"
    # Auto-merge settings
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "bhekanik"
    assignees:
      - "bhekanik"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # Also check GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # Monitor Terraform providers for updates
  - package-ecosystem: "terraform"
    directory: "/terraform/aws"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "terraform"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"