# CI Workflow Template
# Copy this to .github/workflows/ci.yml to enable optimized CI testing

name: CI

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Run linting
      run: npm run lint:check
      
    - name: Run type checking
      run: npm run typecheck
      
    - name: Run tests
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
          echo "Running full test suite including integration tests..."
          npm test
        else
          echo "Running fast test suite (excluding integration tests)..."
          npm run test:fast
        fi
      
    - name: Build
      run: npm run build:all